# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

qr_sign_cpp <- function(A) {
    .Call(`_StealLikeBayes_qr_sign_cpp`, A)
}

rhaar_cpp <- function(n) {
    .Call(`_StealLikeBayes_rhaar_cpp`, n)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_StealLikeBayes_RcppExport_registerCCallable`)
})
